on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'cat package.json'
        run: cat ./package.json
      - name: install node v20
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 20
      - name: npm install
        run: npm install
      - name: tsc
        run: npm run build
      - name: publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: publish to GitHub Packages
        run: |
          echo "@ozmap:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc
          npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
